name= input("enter name:")
Age=int(input("enter age:"))
rollno=int(input("enter rollno:"))
marks=(input("enter marks:"))
grade=(input("enter grade:"))
print("***** Student Details *****")
print("Student name:" ,name)
print("Student Age:" ,Age)
print("Student roll:" ,rollno)
print("Student marks:" ,marks)
print("Student grade:" ,grade)
